package query

import "github.com/anatoly-tenenev/spec-cli/internal/application/help/helpmodel"

func HelpSpec() helpmodel.CommandSpec {
	return helpmodel.CommandSpec{
		Name:    "query",
		Summary: "read many entities with structural filters and deterministic pagination",
		Syntaxes: []string{
			"spec-cli query [options]",
		},
		Options: []helpmodel.OptionSpec{
			{
				Name:             "--type",
				ValueSyntax:      "<entity_type>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "entity type keys from Schema.entity",
				Description:      "Early entity type filter.",
			},
			{
				Name:             "--where-json",
				ValueSyntax:      "<json>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    true,
				SchemaDerivation: "where-json.field paths from CLI filter-namespace",
				Description:      "Structural filter JSON expression.",
			},
			{
				Name:             "--select",
				ValueSyntax:      "<field>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "selectors from CLI projection-namespace",
				Description:      "Projection-namespace selector.",
			},
			{
				Name:             "--sort",
				ValueSyntax:      "<field[:asc|desc]>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "sort fields from CLI filter-namespace",
				Description:      "Deterministic sort term.",
			},
			{
				Name:             "--limit",
				ValueSyntax:      "<n>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Page size; integer >= 0; default 100.",
			},
			{
				Name:             "--offset",
				ValueSyntax:      "<n>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Page offset; integer >= 0; default 0.",
			},
		},
		Rules: []string{
			"projection-namespace argument is --select.",
			"filter-namespace arguments are --sort and where-json.field.",
			"projection-namespace selectors: type, id, slug, revision, created_date, updated_date, meta.<name>, refs, refs.<field>, content.raw, content.sections, content.sections.<name>.",
			"filter-namespace leaf paths: type, id, slug, revision, created_date, updated_date, meta.<name>, refs.<field>.resolved, refs.<field>.type, refs.<field>.id, refs.<field>.slug, content.raw, content.sections.<name>.",
			"--type uses schema-derived entity type keys and is not part of projection-namespace or filter-namespace.",
			"If --select is omitted, default projection is type, id, slug, meta and refs.",
			"Query guarantees deterministic ordering.",
			"If --sort is omitted, effective sort is type:asc, then id:asc.",
			"If --sort is provided, effective sort is user sort plus hidden tail type:asc, then id:asc, unless that tail is already present at the end.",
			"where-json logical nodes: {\"op\":\"and\",\"filters\":[...]}, {\"op\":\"or\",\"filters\":[...]}, {\"op\":\"not\",\"filter\":{...}}.",
			"where-json leaf node: {\"field\":\"meta.status\",\"op\":\"eq\",\"value\":\"active\"}.",
			"Leaf operators: eq, neq, in, not_in, exists, not_exists, gt, gte, lt, lte, contains.",
			"exists/not_exists do not use value; in/not_in require array value; all other leaf operators require value.",
			"Allowed where-json fields come from filter-namespace.",
			"content.raw is forbidden in where-json even though it is available in projection-namespace and --sort.",
			"For content.sections.<name> where-json supports contains, exists and not_exists only.",
			"gt/gte/lt/lte are valid only for numbers and YYYY-MM-DD dates; dates compare lexicographically.",
			"Comparison with incompatible type returns INVALID_QUERY, not false.",
			"For enum fields, eq/neq/in/not_in values must belong to enum with case sensitivity, otherwise INVALID_QUERY.",
			"Missing value semantics: exists returns true only when value is present; not_exists returns true only when value is absent; all other leaf operators return false for missing value.",
		},
		Examples: []string{
			"spec-cli query --type feature --select id --select meta.status",
			"spec-cli query --where-json '{\"field\":\"meta.status\",\"op\":\"eq\",\"value\":\"active\"}'",
			"spec-cli query --where-json '{\"op\":\"and\",\"filters\":[{\"field\":\"meta.status\",\"op\":\"eq\",\"value\":\"active\"},{\"field\":\"refs.owner.id\",\"op\":\"eq\",\"value\":\"SVC-2\"}]}'",
			"spec-cli query --where-json '{\"field\":\"content.sections.summary\",\"op\":\"contains\",\"value\":\"retry\"}'",
			"spec-cli query --where-json '{\"field\":\"refs.owner.id\",\"op\":\"eq\",\"value\":\"SVC-2\"}'",
			"spec-cli query --sort updated_date:desc --limit 50 --offset 0",
		},
	}
}
