package query

import "github.com/anatoly-tenenev/spec-cli/internal/application/help/helpmodel"

func HelpSpec() helpmodel.CommandSpec {
	return helpmodel.CommandSpec{
		Name:    "query",
		Summary: "read many entities through a schema-derived read model",
		Syntaxes: []string{
			"spec-cli query [options]",
		},
		OperationModel: []string{
			"query reads many entities through one schema-derived query-item read model.",
			"--type restricts the active entity-type set before planning and filtering.",
			"--select projects fields from that read model.",
			"--sort orders results by sortable read-model paths.",
			"--where evaluates JMESPath truthiness over the same read model.",
		},
		DetailSections: []helpmodel.DetailSectionSpec{
			{
				Title: "Active type set",
				Lines: []string{
					"If `--type` is omitted, all entity types from the specification projection are active.",
					"If `--type` is repeated, only the selected entity types are active.",
					"The query-item read model is the union over the active type set.",
					"Path-based select, sort, and scalar ref detail paths must be compatible across the active type set.",
				},
			},
			{
				Title: "Read model",
				Lines: []string{
					"built-ins:",
					"  - type",
					"  - id",
					"  - slug",
					"  - revision",
					"  - createdDate",
					"  - updatedDate",
					"type-local fields:",
					"  - meta.<meta_field> from the active type set",
					"  - refs.<ref_field> from the active type set",
					"  - content.raw from the active type set",
					"  - content.sections.<section_name> from the active type set",
					"The exact type-local field catalog is defined by the Specification projection.",
				},
			},
			{
				Title: "Read-model path forms",
				Lines: []string{
					"built-in paths:",
					"  - type",
					"  - id",
					"  - slug",
					"  - revision",
					"  - createdDate",
					"  - updatedDate",
					"meta paths:",
					"  - meta.<meta_field>",
					"scalar ref paths:",
					"  - refs.<scalar_ref_field>",
					"  - refs.<scalar_ref_field>.id|type|slug|resolved|reason",
					"array ref paths:",
					"  - refs.<array_ref_field>",
					"  - query expressions may inspect array items as ref objects with id|type|slug|resolved|reason",
					"content paths:",
					"  - content.raw",
					"  - content.sections",
					"  - content.sections.<section_name>",
				},
			},
			{
				Title: "Where language",
				Lines: []string{
					"`--where` accepts a JMESPath expression.",
					"spec-cli does not add project-specific operators or helper functions on top of JMESPath.",
					"Filtering uses JMESPath truthiness; the expression result does not need to be boolean.",
					"`createdDate` and `updatedDate` use date comparison semantics in the where model.",
					"literal forms (syntax only):",
					"  - string: '<string_value>'",
					"  - number: `42`",
					"  - null: `null`",
				},
			},
			{
				Title: "Operation constraints",
				Lines: []string{
					"select:",
					"  - built-in paths",
					"  - meta paths",
					"  - refs",
					"  - refs.<ref_field>",
					"  - scalar ref detail paths refs.<scalar_ref_field>.id|type|slug|resolved|reason",
					"  - content.raw",
					"  - content.sections",
					"  - content.sections.<section_name>",
					"sort:",
					"  - built-in scalar paths",
					"  - meta.<meta_field>",
					"  - scalar ref detail paths refs.<scalar_ref_field>.id|type|slug|resolved|reason",
					"  - content.raw",
					"  - content.sections.<section_name>",
					"where:",
					"  allowed paths:",
					"    - built-in paths",
					"    - meta.<meta_field>",
					"    - refs.<ref_field>",
					"    - scalar ref detail paths refs.<scalar_ref_field>.id|type|slug|resolved|reason",
					"    - content.sections.<section_name>",
					"  forbidden:",
					"    - content root except content.sections...",
					"    - content.raw",
					"    - meta.<ref_field> access for entityRef values",
					"  runtime notes:",
					"    - evaluates against the same query-item read model",
					"    - optional and conditional fields may be absent at runtime",
					"    - use guards or fallbacks when needed",
				},
			},
			{
				Title: "Defaults",
				Lines: []string{
					"default projection:",
					"  - type",
					"  - id",
					"  - slug",
					"  - meta",
					"  - refs",
					"default order:",
					"  - type:asc",
					"  - id:asc",
				},
			},
		},
		Options: []helpmodel.OptionSpec{
			{
				Name:             "--type",
				ValueSyntax:      "<entity_type>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "entity type keys from the specification projection",
				Description:      "Restrict the active entity-type set.",
			},
			{
				Name:             "--where",
				ValueSyntax:      "<expr>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    true,
				SchemaDerivation: "JMESPath expression over the query-item read model",
				Description:      "Evaluate a JMESPath filter over the query-item read model.",
			},
			{
				Name:             "--select",
				ValueSyntax:      "<path>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "selectable paths from the query-item read model",
				Description:      "Select a path from the query-item read model.",
			},
			{
				Name:             "--sort",
				ValueSyntax:      "<path[:asc|desc]>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "sortable paths from the query-item read model",
				Description:      "Sort by a sortable query-item read-model path.",
			},
			{
				Name:             "--limit",
				ValueSyntax:      "<n>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Page size; integer >= 0; default 100.",
			},
			{
				Name:             "--offset",
				ValueSyntax:      "<n>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Page offset; integer >= 0; default 0.",
			},
		},
		Rules: []string{
			"If --type is omitted, all entity types from the specification projection participate.",
			"Only paths compatible with the active type set may be selected, sorted, or used in --where.",
			"If --sort is omitted, effective sort is type:asc, then id:asc.",
			"If --sort is provided, effective sort is user sort plus hidden tail type:asc, then id:asc, unless that exact tail is already present at the end.",
			"entityRef values are addressed through refs.<ref_field>, not meta.<ref_field>.",
			"Selected leaf paths under meta.<meta_field>, refs.<ref_field>, and content.sections.<section_name> materialize as null when absent.",
			"Aggregate selectors meta, refs, and content.sections keep sparse objects and do not synthesize unknown children.",
		},
		Examples: []string{
			"spec-cli query --type <entity_type> --select id --select meta.<meta_field>",
			"spec-cli query --select refs.<ref_field> --select content.sections.<section_name>",
			"spec-cli query --where \"meta.<meta_scalar_field> == '<string_value>'\"",
			"spec-cli query --where \"refs.<scalar_ref_field>.id == '<entity_id>'\"",
			"spec-cli query --where \"contains(content.sections.<section_name> || '', '<substring>')\"",
			"spec-cli query --where \"length(refs.<array_ref_field>[?reason == '<reason_value>']) > `0`\"",
			"spec-cli query --sort updatedDate:desc --limit 50 --offset 0",
			"Available paths, value kinds, and ref cardinality depend on the effective schema.",
		},
	}
}
