package update

import "github.com/anatoly-tenenev/spec-cli/internal/application/help/helpmodel"

func HelpSpec() helpmodel.CommandSpec {
	return helpmodel.CommandSpec{
		Name:    "update",
		Summary: "patch one entity through a schema-derived write model",
		Syntaxes: []string{
			"spec-cli update [options] --id <entity_id>",
		},
		OperationModel: []string{
			"update patches one logical entity document through a schema-derived write model.",
			"--set, --unset, and --set-file operate on writable logical paths.",
			"Whole-body replacement and clear are a separate operation family.",
		},
		DetailSections: []helpmodel.DetailSectionSpec{
			{
				Title: "Write model",
				Lines: []string{
					"writable paths:",
					"  - meta.<meta_field>",
					"  - refs.<ref_field>",
					"  - content.sections.<section_name>",
					"whole-body operations:",
					"  - --content-file",
					"  - --content-stdin",
					"  - --clear-content",
				},
			},
			{
				Title: "Value syntax",
				Lines: []string{
					"`--set` uses `<path=value>`.",
					"Shell quoting applies outside the argument; for non-ref metadata fields the right-hand side is parsed as a YAML value.",
					"Value forms (syntax only)",
					"  - string scalar meta: `meta.<meta_scalar_field>=<string_value>`",
					"  - boolean scalar meta: `meta.<meta_scalar_field>=true`",
					"  - number scalar meta: `meta.<meta_scalar_field>=42`",
					"  - array meta: `meta.<meta_array_field>='[<value_1>, <value_2>]'`",
					"  - scalar entityRef: `refs.<scalar_ref_field>=<entity_id>`",
					"  - array entityRef: `refs.<array_ref_field>='[<entity_id_1>, <entity_id_2>]'`",
					"Actual writable paths, value kinds, and ref cardinality depend on the effective schema.",
					"Empty value after `=` is treated as an empty string and may still fail schema type checks.",
					"`content.sections.<section_name>` values are treated as raw section text, not YAML-decoded values.",
				},
			},
			{
				Title: "Whole-body heading contract",
				Lines: []string{
					"Whole-body serializer uses canonical headings in the form `## <title> {#<section_name>}`.",
					"In the Specification projection, `content.sections.<section_name>.title` is the canonical heading title used by default.",
				},
			},
		},
		Options: []helpmodel.OptionSpec{
			{
				Name:             "--id",
				ValueSyntax:      "<entity_id>",
				TakesValue:       true,
				Required:         true,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Exact target id.",
			},
			{
				Name:             "--set",
				ValueSyntax:      "<path=value>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "writable paths from the entity write model",
				Description:      "Set a writable logical field by path.",
			},
			{
				Name:             "--set-file",
				ValueSyntax:      "<path=file_path>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "section paths from the entity write model",
				Description:      "Set a content section body from file content.",
			},
			{
				Name:             "--unset",
				ValueSyntax:      "<path>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "writable paths from the entity write model",
				Description:      "Unset a writable logical field by path.",
			},
			{
				Name:                    "--content-file",
				ValueSyntax:             "<path>",
				TakesValue:              true,
				Required:                false,
				Repeatable:              false,
				MutuallyExclusiveGroups: []string{"body_operation"},
				SchemaDerived:           false,
				SchemaDerivation:        "none",
				Description:             "Replace whole content from filesystem path.",
			},
			{
				Name:                    "--content-stdin",
				TakesValue:              false,
				Required:                false,
				Repeatable:              false,
				MutuallyExclusiveGroups: []string{"body_operation"},
				SchemaDerived:           false,
				SchemaDerivation:        "none",
				Description:             "Replace whole content from stdin.",
			},
			{
				Name:                    "--clear-content",
				TakesValue:              false,
				Required:                false,
				Repeatable:              false,
				MutuallyExclusiveGroups: []string{"body_operation"},
				SchemaDerived:           false,
				SchemaDerivation:        "none",
				Description:             "Clear whole content.",
			},
			{
				Name:             "--expect-revision",
				ValueSyntax:      "<token>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Optimistic concurrency token for exact-match guard.",
			},
			{
				Name:             "--dry-run",
				TakesValue:       false,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Run full checks without filesystem mutation.",
			},
		},
		Rules: []string{
			"Allowed write paths are derived from the effective schema.",
			"Reference writes use target entity ids, not read-side ref objects produced by query/get.",
			"--set-file is allowed only for content.sections.<section_name>.",
			"Whole-body operations are not write-model paths.",
			"Whole-body serializer emits canonical headings as `## <title> {#<section_name>}`.",
			"Specification projection `title` fields expose canonical heading titles used by default.",
			"Whole-body operations may be combined with meta.<meta_field> and refs.<ref_field> writes.",
			"Built-in fields and aggregate content paths are not writable: type, id, slug, createdDate, updatedDate, content, content.raw, content.sections.",
			"At least one patch operation must be provided.",
			"Whole-body operations and content.sections.<section_name> path-based operations cannot be mixed.",
			"--content-file, --content-stdin and --clear-content are mutually exclusive.",
			"--expect-revision is an optimistic concurrency guard; command fails on revision mismatch.",
		},
		Examples: []string{
			"spec-cli update --id <entity_id> --set meta.<meta_scalar_field>=<string_value>",
			"spec-cli update --id <entity_id> --content-file ./input/body.md --expect-revision <token>",
		},
	}
}
