package update

import "github.com/anatoly-tenenev/spec-cli/internal/application/help/helpmodel"

func HelpSpec() helpmodel.CommandSpec {
	return helpmodel.CommandSpec{
		Name:    "update",
		Summary: "patch one entity by exact id",
		Syntaxes: []string{
			"spec-cli update [options] --id <entity_id>",
		},
		Options: []helpmodel.OptionSpec{
			{
				Name:             "--id",
				ValueSyntax:      "<entity_id>",
				TakesValue:       true,
				Required:         true,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Exact target id.",
			},
			{
				Name:             "--set",
				ValueSyntax:      "<path=value>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "write paths from CLI write-namespace",
				Description:      "Set writable slot by write-namespace path.",
			},
			{
				Name:             "--set-file",
				ValueSyntax:      "<path=file_path>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "content.sections.<name> from raw schema sections",
				Description:      "Set section body from file content.",
			},
			{
				Name:             "--unset",
				ValueSyntax:      "<path>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "write paths from CLI write-namespace",
				Description:      "Unset writable slot by write-namespace path.",
			},
			{
				Name:                    "--content-file",
				ValueSyntax:             "<path>",
				TakesValue:              true,
				Required:                false,
				Repeatable:              false,
				MutuallyExclusiveGroups: []string{"body_operation"},
				SchemaDerived:           false,
				SchemaDerivation:        "none",
				Description:             "Replace whole content from filesystem path.",
			},
			{
				Name:                    "--content-stdin",
				TakesValue:              false,
				Required:                false,
				Repeatable:              false,
				MutuallyExclusiveGroups: []string{"body_operation"},
				SchemaDerived:           false,
				SchemaDerivation:        "none",
				Description:             "Replace whole content from stdin.",
			},
			{
				Name:                    "--clear-content",
				TakesValue:              false,
				Required:                false,
				Repeatable:              false,
				MutuallyExclusiveGroups: []string{"body_operation"},
				SchemaDerived:           false,
				SchemaDerivation:        "none",
				Description:             "Clear whole content.",
			},
			{
				Name:             "--expect-revision",
				ValueSyntax:      "<token>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Optimistic concurrency token for exact-match guard.",
			},
			{
				Name:             "--dry-run",
				TakesValue:       false,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Run full checks without filesystem mutation.",
			},
		},
		Rules: []string{
			"Write-namespace arguments are --set, --set-file and --unset.",
			"Write-namespace paths: meta.<name>, refs.<field>, content.sections.<name>.",
			"Projection from raw schema: non-entity_ref metadata -> meta.<name>; scalar entity_ref metadata -> refs.<field>; sections -> content.sections.<name>.",
			"Allowed write-paths are derived from the effective schema.",
			"refs.<field> values are target entity ids.",
			"--set-file is allowed only for content.sections.<name>.",
			"Whole-body operations are --content-file, --content-stdin and --clear-content; they are not write-namespace paths.",
			"Built-in fields and aggregate content paths are not writable: type, id, slug, created_date, updated_date, content, content.raw, content.sections.",
			"At least one patch operation must be provided.",
			"--unset removes a writable slot by write-namespace path.",
			"Whole-body operations and content.sections.<name> path-based operations cannot be mixed.",
			"--content-file, --content-stdin and --clear-content are mutually exclusive.",
			"--expect-revision is an optimistic concurrency guard; command fails on revision mismatch.",
		},
		Examples: []string{
			"spec-cli update --id FEAT-8 --set meta.status=deprecated",
			"spec-cli update --id FEAT-8 --unset refs.owner",
			"spec-cli update --id FEAT-8 --set-file content.sections.summary=./input/summary.md",
			"spec-cli update --id FEAT-8 --content-file ./input/body.md --expect-revision sha256:...",
		},
	}
}
