package add

import "github.com/anatoly-tenenev/spec-cli/internal/application/help/helpmodel"

func HelpSpec() helpmodel.CommandSpec {
	return helpmodel.CommandSpec{
		Name:    "add",
		Summary: "create one entity through a schema-derived write model",
		Syntaxes: []string{
			"spec-cli add --type <entity_type> --slug <slug> [options]",
		},
		OperationModel: []string{
			"add creates one logical entity document through a schema-derived write model.",
			"Path-based writes target writable logical fields.",
			"Whole-body content input is a separate input mode, not the primary document model.",
		},
		DetailSections: []helpmodel.DetailSectionSpec{
			{
				Title: "Identity and system fields",
				Lines: []string{
					"`type` is chosen by `--type`.",
					"`slug` is chosen by `--slug`.",
					"`id` is derived by the command from the new entity type, the provided slug, and the effective schema.",
					"`createdDate`, `updatedDate`, and `revision` are command-managed built-ins and are not set directly.",
				},
			},
			{
				Title: "Write model",
				Lines: []string{
					"writable paths:",
					"  - meta.<meta_field>",
					"  - refs.<ref_field>",
					"  - content.sections.<section_name>",
					"whole-body operations:",
					"  - --content-file",
					"  - --content-stdin",
				},
			},
			{
				Title: "Value syntax",
				Lines: []string{
					"`--set` uses `<path=value>`.",
					"Shell quoting applies outside the argument; for non-ref metadata fields the right-hand side is parsed as a YAML value.",
					"Value forms (syntax only)",
					"  - string scalar meta: `meta.<meta_scalar_field>=<string_value>`",
					"  - boolean scalar meta: `meta.<meta_scalar_field>=true`",
					"  - number scalar meta: `meta.<meta_scalar_field>=42`",
					"  - array meta: `meta.<meta_array_field>='[<value_1>, <value_2>]'`",
					"  - scalar entityRef: `refs.<scalar_ref_field>=<entity_id>`",
					"  - array entityRef: `refs.<array_ref_field>='[<entity_id_1>, <entity_id_2>]'`",
					"Actual writable paths, value kinds, and ref cardinality depend on the effective schema.",
					"Empty value after `=` is treated as an empty string and may still fail schema type checks.",
					"`content.sections.<section_name>` values are treated as raw section text, not YAML-decoded values.",
				},
			},
			{
				Title: "Whole-body heading contract",
				Lines: []string{
					"Whole-body serializer uses canonical headings in the form `## <title> {#<section_name>}`.",
					"In the Specification projection, `content.sections.<section_name>.title` is the canonical heading title used by default.",
				},
			},
		},
		Options: []helpmodel.OptionSpec{
			{
				Name:             "--type",
				ValueSyntax:      "<entity_type>",
				TakesValue:       true,
				Required:         true,
				Repeatable:       false,
				SchemaDerived:    true,
				SchemaDerivation: "entity type keys from the specification projection",
				Description:      "Target entity type.",
			},
			{
				Name:             "--slug",
				ValueSyntax:      "<slug>",
				TakesValue:       true,
				Required:         true,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Entity slug used to derive the new entity identity in the effective schema.",
			},
			{
				Name:             "--set",
				ValueSyntax:      "<path=value>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "writable paths from the entity write model",
				Description:      "Set a writable logical field by path.",
			},
			{
				Name:             "--set-file",
				ValueSyntax:      "<path=file_path>",
				TakesValue:       true,
				Required:         false,
				Repeatable:       true,
				SchemaDerived:    true,
				SchemaDerivation: "section paths from the entity write model",
				Description:      "Set a content section body from file content.",
			},
			{
				Name:                    "--content-file",
				ValueSyntax:             "<path>",
				TakesValue:              true,
				Required:                false,
				Repeatable:              false,
				MutuallyExclusiveGroups: []string{"content_body_source"},
				SchemaDerived:           false,
				SchemaDerivation:        "none",
				Description:             "Whole-body content source from filesystem path.",
			},
			{
				Name:                    "--content-stdin",
				TakesValue:              false,
				Required:                false,
				Repeatable:              false,
				MutuallyExclusiveGroups: []string{"content_body_source"},
				SchemaDerived:           false,
				SchemaDerivation:        "none",
				Description:             "Whole-body content source from stdin.",
			},
			{
				Name:             "--dry-run",
				TakesValue:       false,
				Required:         false,
				Repeatable:       false,
				SchemaDerived:    false,
				SchemaDerivation: "none",
				Description:      "Run validation and planning without filesystem mutation.",
			},
		},
		Rules: []string{
			"Allowed write paths are derived from the effective schema.",
			"Reference writes use target entity ids, not read-side ref objects produced by query/get.",
			"--set-file is allowed only for content.sections.<section_name>.",
			"Whole-body inputs are not write-model paths.",
			"Whole-body serializer emits canonical headings as `## <title> {#<section_name>}`.",
			"Specification projection `title` fields expose canonical heading titles used by default.",
			"Whole-body inputs may be combined with meta.<meta_field> and refs.<ref_field> writes.",
			"Whole-body inputs cannot be combined with content.sections.<section_name> path-based operations.",
			"Built-in fields and aggregate content paths are not writable: type, id, slug, createdDate, updatedDate, content, content.raw, content.sections.",
			"--content-file and --content-stdin are mutually exclusive.",
		},
		Examples: []string{
			"spec-cli add --type <entity_type> --slug <slug> --set meta.<meta_scalar_field>=<string_value>",
			"spec-cli add --type <entity_type> --slug <slug> --content-file ./input/body.md",
		},
	}
}
